# configuration for https://travis-ci.org/electrumj/electrumj
language: java
jdk:
    - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn clean verify

after_success:
  - mvn test jacoco:report coveralls:report
